--[[
Empyrean +
A forked version of Empyrean 8.1 with additonal features added and bugs fixed.

Credits:
Emper - CREATED THE ORIGINAL "Empyrean Reanimate". THANK HIM FOR THIS!
the.guardian_ - worked on this script
Melon / Cherry - worked on this script

Clean Up Guide:
Use: table.insert(ScriptCache.ActiveConnections, CONNECTION)
for when youre making connections that should disconnect when you reset
^ Examples: Mouse inputs, events, etc (THIS EXPECTS "RBXScriptConnectio")

Use: table.insert(ScriptCache.TrashBin, OBJECT)
for when youre creating objects that should be deleted when you reset
^ Examples: Effects, particles, sounds, etc (THIS EXPECTS AN INSTANCE)


ill write this later LOL
ill write this later LOL
ill write this later LOL
ill write this later LOL
ill write this later LOL
ill write this later LOL
ill write this later LOL

]]
