--[[
                                                                                    
▄▄▄▄▄▄     ▄▄▄▄▄▄  ▄▄▄▄▄      ▄▄▄     ▄▄▄▄▄▄▄   ▄▄▄     ▄▄▄▄▄▄  ▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄ 
█▀██▀▀██   █▀ ██   ██▀▀▀▀█▄   ██▀▀█▄  █▀██▀▀▀   ▀██▀    █▀ ██   █▀██▀▀▀   █▀██▀▀▀  
  ██   ██     ██   ▀██▄  ▄▀   ██ ▄█▀    ██       ██        ██     ██        ██     
  ██   ██     ██     ▀██▄▄    ██▀▀█▄    ████     ██        ██     ████      ███▀   
▄ ██   ██     ██   ▄   ▀██▄ ▄ ██  ▄█    ██       ██        ██     ██      ▄ ██     
▀██▀███▀    ▄▄██▄▄ ▀██████▀ ▀██████▀    ▀█████  ████████ ▄▄██▄▄   ▀█████  ▀██▀     

██████  ██      ██    ██ ███████ 
██   ██ ██      ██    ██ ██      
██████  ██      ██    ██ ███████ 
██      ██      ██    ██      ██ 
██      ███████  ██████  ███████ 
                                 
a silly script i wrote in the span of half if not a full day
this script was meant for studio but i decided to poorly
port it over to the average script exeucutor for your use

Credits: TBA
]]--
