-- [[ Locust : Testing ]] --
-- THIS IS IN TESTING, NOT THE FINAL SCRIPT! --

--[[ 
// Credits | <3
Melon - created everything in the script (excluding pretty much all of the animations and reanimation changes)
Emper - created the reanim used to make this script work ofc
STEVETHEREALONE - created the .anim format
TheGuardian - created anim2rbxm and .anim parser, also did a lot of edits and bug fixes on the reanimate / script (cool guy btw)
imbluuhahaalt_ - created the "Final Night" emote (cool guy btw)
F̷̎͝l̷̄͆ő̵̌ṕ̴̓p̸̃̈́á̷̔  - gave some cool align and overall ideas (cool guy btw)

// Special Thanks | <3
Cherry Club - my beloved community + always sticking with me even through all the burn out ive gone through
Cherry - my extremely cool character + emotional anchor
Kronos / Astron / Saturn - being very cool + very funny and overall amazing person to be with
Diego / Banana - being very cool + killed boredom every second we called, thanks man
Zink - being very cool + always being talkative, always iconic!
the people that draw fanart (in melons baseplate art wall) - cool as HELL for drawing my character + thank you doing something with me in mind, means a lot <3
nil - being very cool + always gave advice when i didnt know who to ask, never forgetting the day we started talking.
]]

--[[
// Hats
[ FREE RIG ]:
https://www.roblox.com/catalog/3398308134/International-Fedora-Canada
https://www.roblox.com/catalog/3409612660/International-Fedora-USA
https://www.roblox.com/catalog/3033908130/International-Fedora-France
https://www.roblox.com/catalog/3033910400/International-Fedora-Germany
https://www.roblox.com/catalog/4819740796/Robox
https://www.roblox.com/catalog/15254947445/24k-Gold-Plunger
https://www.roblox.com/catalog/5552252553/Kinetic-Staff
https://www.roblox.com/catalog/6909084751/Artist-Backpack
https://www.roblox.com/catalog/5354918926/Build-It-Backpack
]]

--[[
// Features
head follows mouse - makes the characters head follow where you are pointing your mouse at (emotes only in bone aka humanoid rig scripts)
animation speed - directly modify how fast / slow you want animations to play (0.1 - 5)
animation blending - directly modify how smooth you want animations to lerp (0 - 1)
rig scale - lets you scale how big your character is which allows the big rigs to be used (0.45 - 7.25)
camera follows head - camera smoothly follows the characters head to allow for some interesting shit idk
emote library support - allows you to import rbxms / rbxmxs (or .anim files) into your workspace folder
for an endless amount of emotes (anim files recommended for more optimization)
walk / sprint speed boxes - lets you directly change speed without modifying the scripts source
scriptless emote library - import a file and audio and your emote will be successfully imported requiring 0 lua editing / scripting
]]

--[[
// Help
for the emote folder please join my discord: https://discord.gg/HuBhaN5h9
file import - all animations MUST match their mp3 (example: gangnam style.anim must be gangnam style.mp3)
it is CASE SENSITIVE meaning mp3s HAVE to match the rbxm / anim file.
]]

loadstring(game:HttpGet("https://raw.githubusercontent.com/MelonsStuff/FEVerse/refs/heads/main/Obfuscations/Locust.luau"))()
