-- [[ RERIlla - RORilla Revived ]] --

--[[
  Credits:
  // saucekid - Created this script
  // Emper - Created the reanimation used
  // Melon - Fixed this script
  // Guardian | TheGuardian - Helped update the reanimate, fixed some bugs and more.
  Note: if there's bugs pls let me know so i can fix them

  Free rig:
  // https://www.roblox.com/catalog/3033910400/International-Fedora-Germany
  // https://www.roblox.com/catalog/3409612660/International-Fedora-USA
  // https://www.roblox.com/catalog/3398308134/International-Fedora-Canada
  // https://www.roblox.com/catalog/3033908130/International-Fedora-France
  // https://www.roblox.com/catalog/4819740796/Robox

  Paid hats are found in this game:
  // https://www.roblox.com/games/15541318313/Melons-Accessory-Store
]] 

--[[
              ████      ████                
            ████████████████████            
          ████████████████████████          
        ████████████████████████████        
        ████████████████████████████        
      ████████████████████████████████      
      ██▒▒▒▒▒▒▒▒██████████████▒▒▒▒████      
      ██▒▒▒▒▒▒▒▒▒▒▒▒██████▒▒▒▒▒▒▒▒▒▒██      
    ▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒    
    ▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    
    ████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██    
    ████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██    
    ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒████    
    ██████████▒▒▒▒▒▒▒▒▒▒░░░░░░▒▒████████    
      ████████▒▒▒▒░░░░░░░░░░▒▒▒▒████████    
      ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒████████      
          ██████████▒▒▒▒▒▒██████████        
        ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒████████      
        ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██████      
      ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒████████    
    ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██████████  
  ██████████  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ████████  
  ████████  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██  ██████████
██████████  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██  ██████████
██████████   ███▒▒▒▒▒▒▒▒▒▒▒▒███   ██████████
▒▒▒▒████▒▒    ████████████████    ▒▒██████▒▒
▒▒▒▒▒▒▒▒▒▒                        ▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒                          ▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒                            ▒▒▒▒▒▒▒▒▒
]]--

loadstring(game:HttpGet("https://raw.githubusercontent.com/MelonsStuff/FEVerse/refs/heads/main/OpenSource/RERilla.luau"))()
